package DataBase;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import projectCalculatorMain.DataBaseDetails;
/**
 *
 * @author Roxven89
 */
public class DataBaseConnector {

    private final String dataBaseHost = "jdbc:derby:C:/Users/Public/ProjectCalculatorDataBase";
    private final String dataBaseHostCreate = "jdbc:derby:C:/Users/Public/ProjectCalculatorDataBase;create=true";
    private final String driver = "org.apache.derby.jdbc.EmbeddedDriver";
    private final String user = "Swarco";
    private final String password = "Swarco";
    
    private final String sqlCreateTableMaterials = "CREATE TABLE MATERIALS " + 
            "( ID INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, " + 
            "MATERIAL_NAME VARCHAR(40), " + 
            "MATERIAL_UNIT VARCHAR(40), " + 
            "MATERIAL_PRICE DECIMAL(12,2), " + 
            "MATERIAL_VAT_RATE VARCHAR(5), " + 
            "MATERIAL_VENDOR VARCHAR(40), " + 
            "MATERIAL_DATE_OF_ENTRY DATE )";
    
    private final String sqlCreateTableSubconstructors = "CREATE TABLE SUBCONSTRUCTORS " + 
            "( ID INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, " + 
            "SUBCONSTRUCTOR_NAME VARCHAR(40), " + 
            "SUBCONSTRUCTOR_UNIT VARCHAR(40), " + 
            "SUBCONSTRUCTOR_PRICE DECIMAL(12,2), " + 
            "SUBCONSTRUCTOR_VAT_RATE VARCHAR(5), " + 
            "SUBCONSTRUCTOR_VENDOR VARCHAR(40), " + 
            "SUBCONSTRUCTOR_DATE_OF_ENTRY DATE )";
    
    private final String sqlCreateTableLabour = "CREATE TABLE LABOUR " + 
            "( ID INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, " +
            "LABOUR_EMPLOYEE_NAME VARCHAR(40), " + 
            "LABOUR_UNIT VARCHAR(40), " + 
            "LABOUR_COST_ DECIMAL(12,2), " + 
            "LABOUR_GROSS_OVERHEAD VARCHAR(5), " + 
            "LABOUR_EMPLOYEE_TYPE VARCHAR(40), " + 
            "LABOUR_DATE_OF_ENTRY DATE )";
    
    private final String sqlCreateTableLogistic = "CREATE TABLE LOGISTIC " + 
            "( ID INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, " + 
            "LOGISTIC_NAME VARCHAR(40), " + 
            "LOGISTIC_UNIT VARCHAR(40), " + 
            "LOGISTIC_PRICE DECIMAL(12,2), " + 
            "LOGISTIC_VAT_RATE VARCHAR(5), " + 
            "LOGISTIC_VENDOR VARCHAR(40), " + 
            "LOGISTIC_DATE_OF_ENTRY DATE )";
    
    private final String sqlCreateTableOtherCosts = "CREATE TABLE OTHERCOSTS " + 
            "( ID INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, " + 
            "OTHERCOSTS_NAME VARCHAR(40), " + 
            "OTHERCOSTS_UNIT VARCHAR(40), " + 
            "OTHERCOSTS_PRICE DECIMAL(12,2), " + 
            "OTHERCOSTS_VAT_RATE VARCHAR(5), " + 
            "OTHERCOSTS_VENDOR VARCHAR(40), " + 
            "OTHERCOSTS_DATE_OF_ENTRY DATE )";
    
    Connection connection;
    DatabaseMetaData metaData;
    Statement statement;
    ObservableList<DataBaseDetails>list;

    public DataBaseConnector() {
        
        addDriver();
        
        try {
            connection = DriverManager.getConnection(dataBaseHost, user, password);
        } catch (SQLException error) {
            System.out.print(error);
            
            try {
                connection = DriverManager.getConnection(dataBaseHostCreate, user, password);
                statement = connection.createStatement();
                
                statement.addBatch(sqlCreateTableMaterials);
                statement.addBatch(sqlCreateTableSubconstructors);
                statement.addBatch(sqlCreateTableLabour);
                statement.addBatch(sqlCreateTableLogistic);
                statement.addBatch(sqlCreateTableOtherCosts);
               
                statement.executeBatch();
                statement.close();
                
            } catch (SQLException errorX) {
                System.out.print(errorX);
            }  
        } finally {
            
            try {
                connection.close();
            } catch (SQLException error) {
                System.out.print(error);
            }
        }
    }
    
    public void connectToDataBase(){
        addDriver();
        try {
            connection = DriverManager.getConnection(dataBaseHost, user, password);
            statement = connection.createStatement();
        } catch (SQLException error) {
            System.out.print(error);
        }
    }
    
    private void addDriver(){
        try {
            Class.forName(driver);
        } catch (java.lang.ClassNotFoundException error) {
            System.out.print(error);
        }
    }
    
    public void addToDataBase(String costType){
        try {
            statement.executeUpdate(costType);
            statement.close();
        } catch (SQLException error) {
             System.out.print(error);
        } finally {
            try {
                connection.close();
            } catch (SQLException error) {
                System.out.print(error);
            }
        }
    }
    
    public void lookForDataBase(String formula, String lookingFraze, TableView tableView, TableColumn column1, TableColumn column2, 
            TableColumn column3, TableColumn column4, TableColumn column5, 
            TableColumn column6){
        
        list = FXCollections.observableArrayList();
        
        try{
            tableView.getItems().clear();
            String sentence = formula + lookingFraze;
            ResultSet result = statement.executeQuery(sentence);
            while(result.next()){
                String name = result.getString(1);
                String unit = result.getString(2);
                String price = String.valueOf(result.getDouble(3));
                String rate = result.getString(4);
                String vendor = result.getString(5);
                String date = String.valueOf(result.getDate(6));
                
                list.add(new DataBaseDetails(name, unit, price, rate, vendor, date));
            }
            statement.close();
        } catch (SQLException error){
             System.out.print(error);
        } finally {
            try {
                connection.close();
            } catch (SQLException error) {
                System.out.print(error);
            }
        }
        
        column1.setCellValueFactory(new PropertyValueFactory<>("name"));
        column2.setCellValueFactory(new PropertyValueFactory<>("unit"));
        column3.setCellValueFactory(new PropertyValueFactory<>("price"));
        column4.setCellValueFactory(new PropertyValueFactory<>("vat"));
        column5.setCellValueFactory(new PropertyValueFactory<>("vendor"));
        column6.setCellValueFactory(new PropertyValueFactory<>("date"));
        
        tableView.setItems(null);
        tableView.setItems(list);
    }
}
